// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCkDoi91M-eXuS30M8gKeg73lq1um6htw',
    appId: '1:250950861411:web:3b21980bbb5d44749eee56',
    messagingSenderId: '250950861411',
    projectId: 'devclub-events-cff77',
    authDomain: 'devclub-events-cff77.firebaseapp.com',
    storageBucket: 'devclub-events-cff77.firebasestorage.app',
    measurementId: 'G-Q0RZ4632RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgoN0WAJSu7aYF63wqg_o6a7pel8biG6U',
    appId: '1:250950861411:android:64d94bb8098b43d39eee56',
    messagingSenderId: '250950861411',
    projectId: 'devclub-events-cff77',
    storageBucket: 'devclub-events-cff77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC19-HBStkkvlF1UwagaC2W_-T2jQBu8bk',
    appId: '1:250950861411:ios:044a22016007e24d9eee56',
    messagingSenderId: '250950861411',
    projectId: 'devclub-events-cff77',
    storageBucket: 'devclub-events-cff77.firebasestorage.app',
    iosBundleId: 'com.example.devclubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC19-HBStkkvlF1UwagaC2W_-T2jQBu8bk',
    appId: '1:250950861411:ios:044a22016007e24d9eee56',
    messagingSenderId: '250950861411',
    projectId: 'devclub-events-cff77',
    storageBucket: 'devclub-events-cff77.firebasestorage.app',
    iosBundleId: 'com.example.devclubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCkDoi91M-eXuS30M8gKeg73lq1um6htw',
    appId: '1:250950861411:web:a7883206b3033c1f9eee56',
    messagingSenderId: '250950861411',
    projectId: 'devclub-events-cff77',
    authDomain: 'devclub-events-cff77.firebaseapp.com',
    storageBucket: 'devclub-events-cff77.firebasestorage.app',
    measurementId: 'G-6WP5R75YQ2',
  );

}